#1.Consider:

 x = torch.tensor([2.0], requires_grad=True)

y = x**2 + 3*x + 1

y.backward()

What is the value inside x.grad?

Explain how PyTorch computed it step-by-step.








In [2]:
import torch
x=torch.tensor([2.0], requires_grad=True)
y=x**2+3*x+1
y.backward()
x.grad


tensor([7.])

x = 2

 ↓

x² + 3x + 1

 ↓

y = 11

 ↓

backward()

 ↓

dy/dx = 2x + 3

 ↓

x = 2 বসায়

 ↓

gradient = 7

 ↓

x.grad = 7


#2.What happens in this case?

 x = torch.tensor([2.0])

 y = x**2

 y.backward()


 Why does it fail?


In [4]:

x = torch.tensor([2.0])

y = x**2

y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [5]:

x = torch.tensor([2.0],requires_grad= True)

y = x**2

y.backward()
x.grad

tensor([4.])

x = 2

│

│  requires_grad = False

↓

y = x²

│

│  No computation graph for gradients

↓

y.backward()

│

↓
❌ Error

Correct version

x = torch.tensor([2.0], requires_grad=True)

y = x**2


y.backward()


print(x.grad)

Output:

tensor([4.])

Because:

y=x**2

dx/
dy
	​=2x

At x=2:

dx/
dy=4


#Note

requires_grad=True tells PyTorch to track the tensor's operations and build a computation graph so that .backward() can calculate its gradients. Without it, gradient tracking is disabled, so y.backward() fails.