In [155]:
import torch
print(torch.__version__)

2.11.0+cu128


In [156]:
if torch.cuda.is_available():
    print("CUDA is available.")
    print("Number of CUDA devices:", torch.cuda.device_count())
    print("Device name:", torch.cuda.get_device_name(0))
    print("CUDA version:", torch.version.cuda)
else:
    print("CUDA is not available.")


CUDA is available.
Number of CUDA devices: 1
Device name: Tesla T4
CUDA version: 12.8


In [157]:
a=torch.empty(2,4)
a

tensor([[1.4133e-03, 4.5625e-41, 1.4133e-03, 4.5625e-41],
        [4.4842e-44, 0.0000e+00, 1.7937e-43, 0.0000e+00]])

In [158]:
type(a)

torch.Tensor

In [159]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [160]:
torch.rand(2,3)

tensor([[0.7775, 0.6179, 0.3379],
        [0.2170, 0.9454, 0.7116]])

In [161]:
torch.manual_seed(100) # change kore na
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [162]:
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

In [163]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [164]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [165]:
torch.linspace(1,10,7) # take 7 unit from 1 to 10

tensor([ 1.0000,  2.5000,  4.0000,  5.5000,  7.0000,  8.5000, 10.0000])

#Shape

In [166]:
x=torch.tensor([[1,2,3],[2,3,5]])
x

tensor([[1, 2, 3],
        [2, 3, 5]])

In [167]:
x.shape

torch.Size([2, 3])

In [168]:
torch.empty_like(x)

tensor([[       1210464896,        1210464688, 72340172838076673],
        [                1,                48,                48]])

In [169]:
x

tensor([[1, 2, 3],
        [2, 3, 5]])

In [170]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [171]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [172]:
torch.rand_like( x , dtype=torch.float32)


tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

#Data types


In [173]:
x.dtype

torch.int64

In [174]:
torch.tensor([1.2,3.4,5.6,4.0],dtype=torch.int32)


tensor([1, 3, 5, 4], dtype=torch.int32)

In [175]:
x=x.to(torch.float32)

In [176]:
x.dtype

torch.float32

# Mathematical Operation

In [177]:
x=torch.tensor([[100,222,33,511],[3,224,522,116]])
x

tensor([[100, 222,  33, 511],
        [  3, 224, 522, 116]])

In [178]:
x+2

tensor([[102, 224,  35, 513],
        [  5, 226, 524, 118]])

In [ ]:
x**2       # POWER

tensor([[ 10000,  49284,   1089, 261121],
        [     9,  50176, 272484,  13456]])

In [180]:
x/2

tensor([[ 50.0000, 111.0000,  16.5000, 255.5000],
        [  1.5000, 112.0000, 261.0000,  58.0000]])

In [181]:
x//2  # floor value gola

tensor([[ 50, 111,  16, 255],
        [  1, 112, 261,  58]])

In [182]:
a= torch.rand(2,3)
b= torch.rand(2,3)


In [183]:
a

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [184]:
b

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [185]:
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [186]:
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [187]:
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [188]:
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [189]:
c=torch.tensor([-1,-2,-3,-4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [190]:
f=torch.tensor([1,2,3,4])
torch.abs(f)

tensor([1, 2, 3, 4])

In [191]:
torch.neg(f)

tensor([-1, -2, -3, -4])

In [192]:
d=torch.tensor([1.2,2.3,4.5,5.6])
torch.round(d)

tensor([1., 2., 4., 6.])

In [193]:
torch.floor(d)

tensor([1., 2., 4., 5.])

In [194]:
torch.clamp(d, min=1,max=2)   # value in 1 to 2

tensor([1.2000, 2.0000, 2.0000, 2.0000])

#Reduction Operation


In [195]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [196]:
torch.sum(e)

tensor(27.)

In [197]:
torch.mean(e) # 28/6=4.667

tensor(4.5000)

In [198]:
torch.sum(e,dim=0) # col wise sum

tensor([9., 9., 9.])

In [199]:
torch.sum(e,dim=1) # row wise sum

tensor([10., 17.])

In [200]:
torch.mean(e,dim=0) # col wise mean

tensor([4.5000, 4.5000, 4.5000])

In [201]:
torch.mean(e,dim=1) # row wise mean

tensor([3.3333, 5.6667])

In [202]:
torch.median(e)

tensor(1.)

In [203]:
torch.median(e,dim=0)

torch.return_types.median(
values=tensor([0., 1., 0.]),
indices=tensor([0, 0, 1]))

In [204]:
torch.min(e)

tensor(0.)

In [205]:
torch.max(e)

tensor(9.)

In [206]:
torch.prod(e)

tensor(0.)

In [207]:
torch.argmax(e)

tensor(2)

In [208]:
torch.argmin(e)

tensor(0)

#matrix operation

In [209]:
f=torch.randint(size=(2,3),low=0,high=10,dtype=torch.int32)
g=torch.randint(size=(3,2),low=0,high=10,dtype=torch.int32)

f


tensor([[7, 0, 0],
        [9, 5, 7]], dtype=torch.int32)

In [210]:
g

tensor([[3, 9],
        [4, 0],
        [5, 7]], dtype=torch.int32)

In [211]:
torch.matmul(f,g)

tensor([[ 21,  63],
        [ 82, 130]], dtype=torch.int32)

In [212]:
torch.transpose(f,0,1)

tensor([[7, 9],
        [0, 5],
        [0, 7]], dtype=torch.int32)

In [213]:
vec1=torch.tensor([1,2])
vec2=torch.tensor([3,4])

In [214]:
torch.dot(vec1,vec2)

tensor(11)

# comparison operation

In [215]:
i=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
j=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)




In [216]:
i

tensor([[5., 9., 9.],
        [7., 5., 9.]])

In [217]:
j

tensor([[8., 9., 7.],
        [9., 2., 6.]])

In [218]:
i>j

tensor([[False, False,  True],
        [False,  True,  True]])

In [219]:
i!=j

tensor([[ True, False,  True],
        [ True,  True,  True]])

In [220]:
i==j

tensor([[False,  True, False],
        [False, False, False]])

#special fun

In [221]:
k=torch.tensor([1.2,1.3,4.5,5.4])

In [222]:
torch.log(k)

tensor([0.1823, 0.2624, 1.5041, 1.6864])

In [223]:
torch.exp(k)

tensor([  3.3201,   3.6693,  90.0171, 221.4064])

In [224]:
torch.sigmoid(k)

tensor([0.7685, 0.7858, 0.9890, 0.9955])

In [225]:
torch.softmax(k.float(),dim=0)

tensor([0.0104, 0.0115, 0.2827, 0.6953])

In [226]:
torch.relu(k)

tensor([1.2000, 1.3000, 4.5000, 5.4000])

#inplace operation

In [227]:
m=torch.rand(2,3)
n=torch.rand(2,3)

In [228]:
m

tensor([[0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356]])

In [229]:
n

tensor([[0.3039, 0.6726, 0.5740],
        [0.9233, 0.9178, 0.7590]])

In [230]:
m.add_(n)

tensor([[0.9251, 1.2256, 1.2636],
        [1.2920, 1.8231, 1.5946]])

In [231]:
m  # m change

tensor([[0.9251, 1.2256, 1.2636],
        [1.2920, 1.8231, 1.5946]])

In [232]:
torch.relu_(m)

tensor([[0.9251, 1.2256, 1.2636],
        [1.2920, 1.8231, 1.5946]])

In [233]:
a=torch.tensor([1,2,3,4])
b=a

In [234]:
b[2]=10
b

tensor([ 1,  2, 10,  4])

In [235]:
a   #a also change

tensor([ 1,  2, 10,  4])

In [236]:
a=torch.tensor([1,2,3,4])

In [237]:
b=a.clone()
b

tensor([1, 2, 3, 4])

In [238]:
id(a)

139835473198720

In [239]:
id(b)

139835473191280